name       : libchamplain
version    : 0.12.20
release    : 22
source     :
    - https://download.gnome.org/sources/libchamplain/0.12/libchamplain-0.12.20.tar.xz : 0232b4bfcd130a1c5bda7b6aec266bf2d06e701e8093df1886f1e26bc1ba3066
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Clutter Map Widget
description: |
    libchamplain is a C library providing a ClutterActor to display maps. It also provides a Gtk+ widget to display maps in Gtk+ applications. Python and Perl bindings are also available. It supports numerous free map sources such as OpenStreetMap, OpenCycleMap, OpenAerialMap and Maps for free.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
