name       : libchamplain
version    : 0.12.15
release    : 11
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/libchamplain/0.12/libchamplain-0.12.15.tar.xz : 54721a210bdef6d73c5192ed83542023117bf5d7441257e7a7a9f8c05550b874
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : Clutter Map Widget
description: |
    libchamplain is a C library providing a ClutterActor to display maps. It also provides a Gtk+ widget to display maps in Gtk+ applications. Python and Perl bindings are also available. It supports numerous free map sources such as OpenStreetMap, OpenCycleMap, OpenAerialMap and Maps for free.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - vala
setup      : |
    %configure --disable-static \
               --enable-vala \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
