name       : libchamplain
version    : 0.12.19
release    : 16
source     :
    - https://download.gnome.org/sources/libchamplain/0.12/libchamplain-0.12.19.tar.xz : 36842e326cdbe3cdbdab818472797eedb661dec842fe0579596a3a8d438b2aa4
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Clutter Map Widget
description: |
    libchamplain is a C library providing a ClutterActor to display maps. It also provides a Gtk+ widget to display maps in Gtk+ applications. Python and Perl bindings are also available. It supports numerous free map sources such as OpenStreetMap, OpenCycleMap, OpenAerialMap and Maps for free.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(sqlite3)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    NOCONFIGURE=1 ./autogen.sh
    %configure --disable-static --enable-gtk-doc --enable-introspection --enable-vala
build      : |
    %make
install    : |
    %make_install
