name       : libchamplain
version    : 0.12.13
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libchamplain/0.12/libchamplain-0.12.13.tar.xz : b3b3a44530ac94c0b3c3710a2d9495d47450c4133006c5e3ca24e0a761683fab
license    :
    - LGPL-2.0
summary    : Clutter Map Widget
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(cairo)
    - pkgconfig(sqlite3)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(clutter-gtk-1.0)
    - vala
description: |
    libchamplain is a C library providing a ClutterActor to display maps. It also provides a Gtk+ widget to display maps in Gtk+ applications. Python and Perl bindings are also available. It supports numerous free map sources such as OpenStreetMap, OpenCycleMap, OpenAerialMap and Maps for free.
setup      : |
    %configure --disable-static \
               --enable-vala \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
