name       : libchamplain
version    : 0.12.21
release    : 23
source     :
    - https://download.gnome.org/sources/libchamplain/0.12/libchamplain-0.12.21.tar.xz : a915cd172a0c52944c5579fcb4683f8a878c571bf5e928254b5dafefc727e5a7
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : Clutter Map Widget
description: |
    libchamplain is a C library providing a ClutterActor to display maps. It also provides a Gtk+ widget to display maps in Gtk+ applications. Python and Perl bindings are also available. It supports numerous free map sources such as OpenStreetMap, OpenCycleMap, OpenAerialMap and Maps for free.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gdk-3.0)
    - pkgconfig(libsoup-3.0)
    - pkgconfig(sqlite3)
    - gnome-common
    - gtk-doc
    - vala
setup      : |
    %meson_configure -Dgtk_doc=true
build      : |
    %ninja_build
install    : |
    %ninja_install
