name        : libchamplain
version     : 0.12.11
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/libchamplain/0.12/libchamplain-0.12.11.tar.xz : 851e24888d967c10acb8fd878df1292a84b8180eb4c48fc5bfbf1a48896d4aa5
license     :
    - LGPL-2.0
summary     : Clutter Map Widget
builddeps   :
    - pkgconfig(gdk-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(cairo)
    - pkgconfig(sqlite3)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(clutter-gtk-1.0)
    - vala
description : |
    libchamplain is a C library providing a ClutterActor to display maps. It also provides a Gtk+ widget to display maps in Gtk+ applications. Python and Perl bindings are also available. It supports numerous free map sources such as OpenStreetMap, OpenCycleMap, OpenAerialMap and Maps for free.
setup      : |
    %configure --disable-static \
               --enable-vala \
               --enable-introspection
build      : |
    %make
install    : |
    %make_install
